//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PSD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public int Id { get; set; }
        public System.DateTime ShowTime { get; set; }
        public bool Availablity { get; set; }
        public int ShowId { get; set; }
    
        public virtual Show Show { get; set; }
    }
}
